language: go

go:
- 1.12.x

env:
  - GO111MODULE=on

jobs:
  include:
    - stage: build
      script:
        - go get ./...
        - go test ./...
        - ./build.sh
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        skip_cleanup: true
        file_glob: true
        file: ./bin/*
        on:
          branch: master
          tags: true

